#include "Global.h"

std::string Global::DATA_FILE_NAME = "data.txt";
float Global::LEARNING_COEFFICIENT = 0.8;
// For Naive Bayes
std::string Global::PARAMETERS_NAIVE_BAYES_FILE_NAME = "Naive_Bayes_optimal_parameters.txt";
std::string Global::NB_OPTIMAL_INTERVAL_COUNT_DIAMETER_STRING = "NB_OPTIMAL_INTERVAL_COUNT_DIAMETER_STRING";
std::string Global::NB_OPTIMAL_INTERVAL_COUNT_LENGTH_STRING = "NB_OPTIMAL_INTERVAL_COUNT_LENGTH_STRING";
std::string Global::NB_OPTIMAL_INTERVAL_COUNT_HEIGHT_STRING = "NB_OPTIMAL_INTERVAL_COUNT_HEIGHT_STRING";
std::string Global::NB_OPTIMAL_INTERVAL_COUNT_WHOLE_WEIGHT_STRING = "NB_OPTIMAL_INTERVAL_COUNT_WHOLE_WEIGHT_STRING";
std::string Global::NB_OPTIMAL_INTERVAL_COUNT_VISCERA_WEIGHT_STRING = "NB_OPTIMAL_INTERVAL_COUNT_VISCERA_WEIGHT_STRING";
std::string Global::NB_OPTIMAL_INTERVAL_COUNT_SHELL_WEIGHT_STRING = "NB_OPTIMAL_INTERVAL_COUNT_SHELL_WEIGHT_STRING";
std::string Global::NB_OPTIMAL_INTERVAL_COUNT_SHUCKED_WEIGHT_STRING = "NB_OPTIMAL_INTERVAL_COUNT_SHUCKED_WEIGHT_STRING";